//**************************************************************************
//Name: Entity Class
//Author: T4
//Description: 该类由T4模板自动生成,重新生成会覆盖该类,请不要在该类写代码！
//**************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Goering.Model.Models; 

namespace Goering.Model.Models.EVN.AutoGenerated
{
	/// <summary>
        /// TN_APPLY_FOR
        /// </summary>
	[Serializable]
    public class TNAPPLYFORInfoParent:BaseEntity
    {
		#region 构造函数

        public TNAPPLYFORInfoParent()
        {
            // Primary Key       
			base.PKeys = new List<string>() { "CN_ID" };
        }
		#endregion


		 #region 属性

		 
		/// <summary>
        /// 主键
        /// </summary>
		[DisplayName(@"主键")]  
		public string CN_ID { get; set; }      
		 
		/// <summary>
        /// 姓名
        /// </summary>
		[DisplayName(@"姓名")]  
		public string CN_NAME { get; set; }      
		 
		/// <summary>
        /// 手机号码
        /// </summary>
		[DisplayName(@"手机号码")]  
		public string CN_PHONE_NUMBER { get; set; }      
		 
		/// <summary>
        /// 身份证
        /// </summary>
		[DisplayName(@"身份证")]  
		public string CN_IDENTITY_CARD { get; set; }      
		 
		/// <summary>
        /// 备注
        /// </summary>
		[DisplayName(@"备注")]  
		public string CN_REMARK { get; set; }      
		 
		/// <summary>
        /// 简历路径
        /// </summary>
		[DisplayName(@"简历路径")]  
		public string CN_RESUME_PATH { get; set; }      
		 
		/// <summary>
        /// 职位ID
        /// </summary>
		[DisplayName(@"职位ID")]  
		public string CR_JOB_ID { get; set; }      
		 
		/// <summary>
        /// 创建时间
        /// </summary>
		[DisplayName(@"创建时间")]  
		public DateTime CN_CREATE_DATE { get; set; }      
		 
		/// <summary>
        /// CN_IS_LOOK
        /// </summary>
		[DisplayName(@"CN_IS_LOOK")]  
		public bool? CN_IS_LOOK { get; set; }      
		 		 
		 #endregion

    }

}

