//**************************************************************************
//Name: Entity Class
//Author: T4
//Description: 该类由T4模板自动生成,重新生成会覆盖该类,请不要在该类写代码！
//**************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Goering.Model.Models; 

namespace Goering.Model.Models.EVN.AutoGenerated
{
	/// <summary>
        /// 招聘职位
        /// </summary>
	[Serializable]
    public class TNJOBInfoParent:BaseEntity
    {
		#region 构造函数

        public TNJOBInfoParent()
        {
            // Primary Key       
			base.PKeys = new List<string>() { "CN_ID" };
        }
		#endregion


		 #region 属性

		 
		/// <summary>
        /// 主键
        /// </summary>
		[DisplayName(@"主键")]  
		public string CN_ID { get; set; }      
		 
		/// <summary>
        /// 名称
        /// </summary>
		[DisplayName(@"名称")]  
		public string CN_NAME { get; set; }      
		 
		/// <summary>
        /// 工作地区
        /// </summary>
		[DisplayName(@"工作地区")]  
		public string CR_WORK_AREA_ID { get; set; }      
		 
		/// <summary>
        /// 月薪范围
        /// </summary>
		[DisplayName(@"月薪范围")]  
		public string CN_MONTHLY_PAY { get; set; }      
		 
		/// <summary>
        /// 招聘人数
        /// </summary>
		[DisplayName(@"招聘人数")]  
		public int? CN_RECRUITIMENT_NUMBER { get; set; }      
		 
		/// <summary>
        /// 学历要求
        /// </summary>
		[DisplayName(@"学历要求")]  
		public string CN_EDUCATIONAL_REQUIREMENTS_ID { get; set; }      
		 
		/// <summary>
        /// 年龄要求
        /// </summary>
		[DisplayName(@"年龄要求")]  
		public string CN_AGE { get; set; }      
		 
		/// <summary>
        /// 工作经验
        /// </summary>
		[DisplayName(@"工作经验")]  
		public string CN_WORK_EXPERIENCE { get; set; }      
		 
		/// <summary>
        /// 联系方式
        /// </summary>
		[DisplayName(@"联系方式")]  
		public string CN_CONTACT { get; set; }      
		 
		/// <summary>
        /// 具体要求
        /// </summary>
		[DisplayName(@"具体要求")]  
		public string CN_REQUIREMENT_DETAIL { get; set; }      
		 
		/// <summary>
        /// 是否上传简历
        /// </summary>
		[DisplayName(@"是否上传简历")]  
		public bool? CN_IS_RESUME { get; set; }      
		 
		/// <summary>
        /// 住宿情况
        /// </summary>
		[DisplayName(@"住宿情况")]  
		public string CN_PUT_UP { get; set; }      
		 
		/// <summary>
        /// 发布日期
        /// </summary>
		[DisplayName(@"发布日期")]  
		public DateTime? CN_PUBLISHED_DATE { get; set; }      
		 
		/// <summary>
        /// 截止日期
        /// </summary>
		[DisplayName(@"截止日期")]  
		public DateTime? CN_EXPIRY_DATE { get; set; }      
		 
		/// <summary>
        /// 创建人
        /// </summary>
		[DisplayName(@"创建人")]  
		public string CR_CREATE_USER_ID { get; set; }      
		 
		/// <summary>
        /// 创建时间
        /// </summary>
		[DisplayName(@"创建时间")]  
		public DateTime CN_CREATE_DATE { get; set; }      
		 
		/// <summary>
        /// 修改人
        /// </summary>
		[DisplayName(@"修改人")]  
		public string CR_MODIFY_USER_ID { get; set; }      
		 
		/// <summary>
        /// 修改时间
        /// </summary>
		[DisplayName(@"修改时间")]  
		public DateTime? CN_MODIFY_DATE { get; set; }      
		 		 
		 #endregion

    }

}

