//**************************************************************************
//Name: Entity Class
//Author: T4
//Description: 该类由T4模板自动生成,重新生成会覆盖该类,请不要在该类写代码！
//**************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Goering.Model.Models; 

namespace Goering.Model.Models.EVN.AutoGenerated
{
	/// <summary>
        /// 月刊
        /// </summary>
	[Serializable]
    public class TNMONTHLYInfoParent:BaseEntity
    {
		#region 构造函数

        public TNMONTHLYInfoParent()
        {
            // Primary Key       
			base.PKeys = new List<string>() { "CN_ID" };
        }
		#endregion


		 #region 属性

		 
		/// <summary>
        /// 主键
        /// </summary>
		[DisplayName(@"主键")]  
		public string CN_ID { get; set; }      
		 
		/// <summary>
        /// 期数
        /// </summary>
		[DisplayName(@"期数")]  
		public int? CN_NUMBER { get; set; }      
		 
		/// <summary>
        /// 创建人
        /// </summary>
		[DisplayName(@"创建人")]  
		public string CR_CREATE_USER_ID { get; set; }      
		 
		/// <summary>
        /// 首页图片路径
        /// </summary>
		[DisplayName(@"首页图片路径")]  
		public string CN_FIRST_PIC_URL { get; set; }      
		 
		/// <summary>
        /// 创建时间
        /// </summary>
		[DisplayName(@"创建时间")]  
		public DateTime CN_CREATE_DATE { get; set; }      
		 		 
		 #endregion

    }

}

