//**************************************************************************
//Name: Entity Class
//Author: T4
//Description: 该类由T4模板自动生成,重新生成会覆盖该类,请不要在该类写代码！
//**************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Goering.Model.Models; 

namespace Goering.Model.Models.EVN.AutoGenerated
{
	/// <summary>
        /// 相关视频
        /// </summary>
	[Serializable]
    public class TNNEWSVIDEOInfoParent:BaseEntity
    {
		#region 构造函数

        public TNNEWSVIDEOInfoParent()
        {
            // Primary Key       
			base.PKeys = new List<string>() { "CN_ID" };
        }
		#endregion


		 #region 属性

		 
		/// <summary>
        /// 主键
        /// </summary>
		[DisplayName(@"主键")]  
		public string CN_ID { get; set; }      
		 
		/// <summary>
        /// 名称
        /// </summary>
		[DisplayName(@"名称")]  
		public string CN_NAME { get; set; }      
		 
		/// <summary>
        /// 文件路径
        /// </summary>
		[DisplayName(@"文件路径")]  
		public string CN_VIDEO_PATH { get; set; }      
		 
		/// <summary>
        /// 动态ID
        /// </summary>
		[DisplayName(@"动态ID")]  
		public string CR_NEWS_ID { get; set; }      
		 
		/// <summary>
        /// 创建人
        /// </summary>
		[DisplayName(@"创建人")]  
		public string CR_CREATE_USER_ID { get; set; }      
		 
		/// <summary>
        /// 创建时间
        /// </summary>
		[DisplayName(@"创建时间")]  
		public DateTime CN_CREATE_DATE { get; set; }      
		 		 
		 #endregion

    }

}

