//**************************************************************************
//Name: Entity Class
//Author: T4
//Description: 该类由T4模板自动生成,重新生成会覆盖该类,请不要在该类写代码！
//**************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Goering.Model.Models; 

namespace Goering.Model.Models.EVN.AutoGenerated
{
	/// <summary>
        /// TN_SUBPROJECT
        /// </summary>
	[Serializable]
    public class TNSUBPROJECTInfoParent:BaseEntity
    {
		#region 构造函数

        public TNSUBPROJECTInfoParent()
        {
            // Primary Key       
			base.PKeys = new List<string>() { "CN_ID" };
        }
		#endregion


		 #region 属性

		 
		/// <summary>
        /// CN_ID
        /// </summary>
		[DisplayName(@"CN_ID")]  
		public string CN_ID { get; set; }      
		 
		/// <summary>
        /// CR_PROJECT_ID
        /// </summary>
		[DisplayName(@"CR_PROJECT_ID")]  
		public string CR_PROJECT_ID { get; set; }      
		 
		/// <summary>
        /// CN_NAME
        /// </summary>
		[DisplayName(@"CN_NAME")]  
		public string CN_NAME { get; set; }      
		 
		/// <summary>
        /// CN_URL
        /// </summary>
		[DisplayName(@"CN_URL")]  
		public string CN_URL { get; set; }      
		 
		/// <summary>
        /// 排序，小的排前面
        /// </summary>
		[DisplayName(@"排序，小的排前面")]  
		public int CN_SORT { get; set; }      
		 
		/// <summary>
        /// CN_IS_ENABLE
        /// </summary>
		[DisplayName(@"CN_IS_ENABLE")]  
		public bool CN_IS_ENABLE { get; set; }      
		 
		/// <summary>
        /// 创建人
        /// </summary>
		[DisplayName(@"创建人")]  
		public string CR_CREATE_USER_ID { get; set; }      
		 
		/// <summary>
        /// 创建时间
        /// </summary>
		[DisplayName(@"创建时间")]  
		public DateTime CN_CREATE_DATE { get; set; }      
		 
		/// <summary>
        /// 修改人
        /// </summary>
		[DisplayName(@"修改人")]  
		public string CR_MODIFY_USER_ID { get; set; }      
		 
		/// <summary>
        /// 修改时间
        /// </summary>
		[DisplayName(@"修改时间")]  
		public DateTime? CN_MODIFY_DATE { get; set; }      
		 		 
		 #endregion

    }

}

