//**************************************************************************
//Name: Entity Class
//Author: T4
//Description: 该类由T4模板自动生成,重新生成会覆盖该类,请不要在该类写代码！
//**************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Goering.Model.Models; 

namespace Goering.Model.Models.EVN.AutoGenerated
{
	/// <summary>
        /// TS_MENU
        /// </summary>
	[Serializable]
    public class TSMENUInfoParent:BaseEntity
    {
		#region 构造函数

        public TSMENUInfoParent()
        {
            // Primary Key       
			base.PKeys = new List<string>() { "CN_ID" };
        }
		#endregion


		 #region 属性

		 
		/// <summary>
        /// 主键
        /// </summary>
		[DisplayName(@"主键")]  
		public string CN_ID { get; set; }      
		 
		/// <summary>
        /// 名称
        /// </summary>
		[DisplayName(@"名称")]  
		public string CN_NAME { get; set; }      
		 
		/// <summary>
        /// 父级ID
        /// </summary>
		[DisplayName(@"父级ID")]  
		public string CR_PARENT_ID { get; set; }      
		 
		/// <summary>
        /// 链接地址
        /// </summary>
		[DisplayName(@"链接地址")]  
		public string CN_LINK_URL { get; set; }      
		 
		/// <summary>
        /// 排序，小的排前面
        /// </summary>
		[DisplayName(@"排序，小的排前面")]  
		public int? CN_SORT { get; set; }      
		 		 
		 #endregion

    }

}

