//**************************************************************************
//Name: Entity Class
//Author: T4
//Description: 该类由T4模板自动生成,重新生成会覆盖该类,请不要在该类写代码！
//**************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Goering.Model.Models; 

namespace Goering.Model.Models.EVN.AutoGenerated
{
	/// <summary>
        /// TS_USER
        /// </summary>
	[Serializable]
    public class TSUSERInfoParent:BaseEntity
    {
		#region 构造函数

        public TSUSERInfoParent()
        {
            // Primary Key       
			base.PKeys = new List<string>() { "CN_ID" };
        }
		#endregion


		 #region 属性

		 
		/// <summary>
        /// 主键
        /// </summary>
		[DisplayName(@"主键")]  
		public string CN_ID { get; set; }      
		 
		/// <summary>
        /// 登录名
        /// </summary>
		[DisplayName(@"登录名")]  
		public string CN_LOGIN_NAME { get; set; }      
		 
		/// <summary>
        /// 密码
        /// </summary>
		[DisplayName(@"密码")]  
		public string CN_PASSWORD { get; set; }      
		 
		/// <summary>
        /// 工号
        /// </summary>
		[DisplayName(@"工号")]  
		public string CN_EMPLOYEE_NO { get; set; }      
		 
		/// <summary>
        /// 真实姓名
        /// </summary>
		[DisplayName(@"真实姓名")]  
		public string CN_REALLY_NAME { get; set; }      
		 
		/// <summary>
        /// 创建人
        /// </summary>
		[DisplayName(@"创建人")]  
		public string CR_CREATE_USER_ID { get; set; }      
		 
		/// <summary>
        /// 创建时间
        /// </summary>
		[DisplayName(@"创建时间")]  
		public DateTime? CN_CREATE_DATE { get; set; }      
		 
		/// <summary>
        /// 修改人
        /// </summary>
		[DisplayName(@"修改人")]  
		public string CR_MODIFY_USER_ID { get; set; }      
		 
		/// <summary>
        /// 修改时间
        /// </summary>
		[DisplayName(@"修改时间")]  
		public DateTime? CN_MODIFY_DATE { get; set; }      
		 		 
		 #endregion

    }

}

