//**************************************************************************
//Name: Entity Class
//Author: T4
//Description: 该类由T4模板自动生成,重新生成不会覆盖该类。
//**************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Goering.Model.Models.EVN.AutoGenerated; 

namespace Goering.Model.Models.EVN
{
	/// <summary>
        /// 招聘职位
        /// </summary>
	[Serializable]
    public class TNJOBInfo:TNJOBInfoParent
    {
		#region 构造函数
        public TNJOBInfo()
        {
            
        }
		#endregion

        public virtual TNWORKAREAInfo TNWORKAREA{ get;set; }

        public virtual TNEDUCATIONALREQUIREMENTSInfo TNEDUCATIONALREQUIREMENTS{ get;set; }

        /// <summary>
        /// 工作地区
        /// </summary>
        [NotMapped]
        public string WorkAreaName
        {
            get
            {
                if (TNWORKAREA!=null)
                {
                    return TNWORKAREA.CN_NAME;
                }
                else
                {
                    return "";
                }
            }
        }

        /// <summary>
        /// 学历要求
        /// </summary>
        [NotMapped]
        public string REQUIREMENTSName
        {
            get
            {
                if (TNEDUCATIONALREQUIREMENTS!=null)
                {
                    return TNEDUCATIONALREQUIREMENTS.CN_NAME;
                }
                else
                {
                    return "";
                }
            }
        }

        /// <summary>
        /// 是否上传简历
        /// </summary>
        [NotMapped]
        public string IsResume
        {
            get
            {
                return this.CN_IS_RESUME.Value == true ? "true" : "false";
            }
        }
    }

}

