//**************************************************************************
//Name: Entity Class
//Author: T4
//Description: 该类由T4模板自动生成,重新生成不会覆盖该类。
//**************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Goering.Model.Models.EVN.AutoGenerated; 

namespace Goering.Model.Models.EVN
{
	/// <summary>
        /// TN_SUBPROJECT
        /// </summary>
	[Serializable]
    public class TNSUBPROJECTInfo:TNSUBPROJECTInfoParent
    {
		#region 构造函数
        public TNSUBPROJECTInfo()
        {
            
        }
		#endregion

        [NotMapped]
        public string PROJECT_NAME { get; set; }
    }

}

